### ISSUE TITLE
Ignite migration

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-4-migration-guide#18]
Vert.x Ignite does not depend on `ignite-spring` by default in Vert.x 4.

Users who configure the grid by providing an XML file shall either:

- migrate to the new JSON config format, or
- add `ignite-spring` dependencies again

**Comment by tsegismont** [comment]
@zyclonite can you take care of this one please?

**Comment by zyclonite** [comment]
pr will be: https://github.com/vert-x3/vertx-4-migration-guide/pull/19

**Comment by zyclonite** [comment]
@tsegismont please review

**Comment by tsegismont** [comment]
Fixed in #19
