### ISSUE TITLE
Rename asciidoc attributes starting with a number

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-4-migration-guide#31]
Currently there are two Asciidoc attributes starting with a number that cannot be substituted when we build the HTML output: `{4}` and `{3x}`.

We can rename them to `{v4}` and `{v3x}`

**Comment by vietj** [comment]
@sangeetaraghu is that fine with you ?

**Comment by sangeetaraghu** [comment]
@vietj yes that sounds ok. No problem. Do you want me to search-replace and push the files maybe later today?

**Comment by vietj** [comment]
yes please
