### ISSUE TITLE
Consider moving the Vert.x Web GraphQL section

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-4-migration-guide#34]
The _Changes in Vert.x Web GraphQL_ section should be moved to _Vert.x Web_ instead of _Miscellaneous Changes_

**Comment by sangeetaraghu** [comment]
@tsegismont Move the _Vert.x Web GraphQL_ chapter under _Vert.x Web_ or place it directly under the Changes in common components main section?

**Comment by tsegismont** [comment]
Good point. Given Vert.x Web GraphQL is documented separately, we could
move it as a top level section indeed.

**Comment by sangeetaraghu** [comment]
Fixed this issue in:
https://github.com/vert-x3/vertx-4-migration-guide/pull/33
