### ISSUE TITLE
Missing information about which client is used in use future methods for asynchronous operations

### ISSUE THREAD

**Issue by akoniar** [vert-x3/vertx-4-migration-guide#42]
### Context

In section "[Use future methods for asynchronous operations](https://github.com/vert-x3/vertx-4-migration-guide/blob/master/asciidoc/modules/con_mg_use-future-methods-for-asynchronous-operations.adoc)" I missing information which client is used here. In first two examples I thinks should be added the line:
`WebClient client = WebClient.create(vertx);`

**Comment by akoniar** [comment]
@sangeetaraghu WDYT?

**Comment by sangeetaraghu** [comment]
@akoniar Added `WebClient client = WebClient.create(vertx);' in the first two examples that shows operations. 
PR:
https://github.com/vert-x3/vertx-4-migration-guide/pull/47
