### ISSUE TITLE
Typo in "Handling deprecations and removals" section

### ISSUE THREAD

**Issue by akoniar** [vert-x3/vertx-4-migration-guide#43]
### Questions

@sangeetaraghu why in last example in this section [Handling deprecations and removals](https://github.com/vert-x3/vertx-4-migration-guide/blob/master/asciidoc/modules/con_mg_handling_deprecations_and_removals.adoc) contains the comment 
`// New method can be used in Vert.x 3.x and Vert.x 4.x releases`

I suppose here comment `// New method can be used in Vert.x 4.x releases`

**Comment by sangeetaraghu** [comment]
@akoniar As discussed, retaining "// New method can be used in Vert.x 3.x and Vert.x 4.x releases".
