### ISSUE TITLE
The get, post, put method aren't present in HttpClient in Vert.x 4.0.0

### ISSUE THREAD

**Issue by akoniar** [vert-x3/vertx-4-migration-guide#46]
@sangeetaraghu In this section [HTTP client request and response methods take an asynchronous handler as input argument](https://github.com/vert-x3/vertx-4-migration-guide/blob/master/asciidoc/modules/con_mg_improvements-in-vertx-http-client.adoc) you mentioning that get, put ... methods have present in HttpClient but since Vert.x 4.0.0. these method has been replaced with request(HttpMethod, ...)
<img width="1344" alt="Screenshot 2020-12-07 at 22 37 45" src="https://user-images.githubusercontent.com/32509391/101408830-4581e280-38dd-11eb-8b6a-4dd6768a119c.png">

**Comment by akoniar** [comment]
@sangeetaraghu  It more like example from vert.x 3.x.x

**Comment by sangeetaraghu** [comment]
PR:
https://github.com/vert-x3/vertx-4-migration-guide/pull/47

@akoniar As discussed, updated the section in bold:

The following examples show how to send a request in **{VertX} {v3x}.**

* To perform a GET operation:
+
[source,java,options="nowrap",subs="attributes+"]
----
Future<HttpClientResponse> f1 = client.get(8080, "localhost", "/uri", HttpHeaders.set("foo", "bar"));
----

* To POST with a buffer body:
+
[source,java,options="nowrap",subs="attributes+"]
----
Future<HttpClientResponse> f2 = client.post(8080, "localhost", "/uri", HttpHeaders.set("foo", "bar"), Buffer.buffer("some-data"));
----

* To POST with a streaming body:
+
[source,java,options="nowrap",subs="attributes+"]
----
Future<HttpClientResponse> f3 = client.post(8080, "localhost", "/uri", HttpHeaders.set("foo", "bar"), asyncFile);
----

In {VertX} {v4}, **you can use the `HttpClientRequest.request()` methods to create an `HttpClientRequest` instance.** These methods can be used in basic interactions such as:
