### ISSUE TITLE
The HTTP version checking calling HttpServerRequest.version paragraphs are repeated on different sections

### ISSUE THREAD

**Issue by jcarranzan** [vert-x3/vertx-4-migration-guide#51]
### Context

I encountered these 2 paragraphs are repeated in the migration guide in these sections:

https://github.com/vert-x3/vertx-4-migration-guide/blob/480f8ced6b956016631d9f1a0cfe97276b12ce36/asciidoc/modules/con_mg_changes-in-future.adoc#checking-the-version-of-http-running-on-the-server

https://github.com/vert-x3/vertx-4-migration-guide/blob/480f8ced6b956016631d9f1a0cfe97276b12ce36/asciidoc/modules/con_mg_improvements-in-vertx-http-client.adoc

I think is right to keep it only on the 4.6. Changes in HTTP section.

**Comment by jcarranzan** [comment]
What do you thin @sangeetaraghu ?

**Comment by sangeetaraghu** [comment]
@jcarranzan Thank you for catching this. I agree having it in 4.6 would be relevant. I will make the change

**Comment by jcarranzan** [comment]
Ok, thanks, I've edited one of the links, they were pointing to the same uri in my first comment.

**Comment by sangeetaraghu** [comment]
@jcarranzan I have fixed this issue in the PR:

https://github.com/vert-x3/vertx-4-migration-guide/pull/53
asciidoc/modules/con_mg_changes-in-future.adoc

**Comment by sangeetaraghu** [comment]
@jcarranzan This issue is fixed. Can you please close it?
