### ISSUE TITLE
JWTAuthOptions - Undocumented deprecated methods

### ISSUE THREAD

**Issue by impolitepanda** [vert-x3/vertx-4-migration-guide#52]
### Context

The javadoc of the class https://vertx.io/docs/apidocs/io/vertx/ext/auth/jwt/JWTAuthOptions.html mentions two methods (getPermissionsClaimKey() and setPermissionsClaimKey(String permissionsClaimKey)) as being deprecated.

The migration doc doens't mention them in the related page https://vert-x3.github.io/vertx-4-migration-guide/index.html#deprecated-and-removed-authentication-and-authorization-methods_authentication-and-authorization

Also no help is given on how to adapt code using these methods for use in vertx 4

**Comment by vietj** [comment]
Assigned to you @pmlopes

**Comment by pmlopes** [comment]
Fixed by: https://github.com/vert-x3/vertx-auth/commit/1c48f941453d3e1d8c76f464c5af6689855d04cb

The Auth JWT manual does show how to use the new API and has an example under the `Authorization` section.

https://vertx.io/docs/vertx-auth-jwt/java/#_authorizing_authz
