### ISSUE TITLE
Wrongly labeled code example in "Changes in HTTP"

### ISSUE THREAD

**Issue by kacperfronc** [vert-x3/vertx-4-migration-guide#55]
There is a piece of code in section (under Changes in HTTP client, Sending a simple request):
https://vert-x3.github.io/vertx-4-migration-guide/index.html#changes-in-http_changes-in-common-components

The header over piece of code is:
**The following example shows how to send a GET request in Vert.x 4 release:**
and the code:
```
client.request(HttpMethod.GET, 80, "example.com", "/", ar -> {
  if (ar.succeeded()) {
    HttpClientRequest = ar.result();
    request.send(ar2 -> {
      if (ar2.succeeded()) {
        HttpClientResponse = ar2.result();
        int statusCode = response.statusCode();
        response.body(ar3 -> {
          if (ar3.succeeded()) {
            Buffer body = ar3.result();
            // Handle body entirely
          } else {
            // Handle server error, e.g connection closed
          }
        });
      } else {
        // Handle server error, e.g connection closed
      }
    });
  } else {
    // Deal connection error, e.g the invalid server or invalid SSL certificate
  }
});
```

But that's not Vert.x 4 approach, it's Vert.x 3

**Comment by tsegismont** [comment]
Hi @kacperfronc , this is actually Vert.x 4 code, which shows that handling the different possible issues has been made easier.

Granted, the example does not use `Future` but working with callbacks is not a problem in Vert.x 4.
