### ISSUE TITLE
HttpMethod is not an enum anymore. How to use the HttpMethod interface in 4.0.0?

### ISSUE THREAD

**Issue by j-pel** [vert-x3/vertx-4-migration-guide#60]
### Questions

In Vert.x 3.9.4 we had:
`app.route().handler(CorsHandler.create(".*.").allowedMethod(HttpMethod.GET));`

What's the equivalent form in Vert.x 4.0.0?

### Version

Vert.x 4.0.0

**Comment by vietj** [comment]
Can you handle this @pmlopes ?

**Comment by pmlopes** [comment]
This was mentioned on the wiki:

https://github.com/vert-x3/wiki/wiki/4.0.0-Deprecations-and-breaking-changes#%EF%B8%8F-httpmethod-is-an-interface

The enum is now an interface, the usage is almost the same:

```java
router.route().handler(CorsHandler.create("http://vertx\\.io").allowedMethod(HttpMethod.PUT));
```

**Comment by vietj** [comment]
can you add a node to the migration guide @pmlopes about this if that's not present already ?

**Comment by pmlopes** [comment]
It is already present as a full description here: https://github.com/vert-x3/vertx-4-migration-guide/blob/ebe693ccbdd49e0d4082788d7c6d5c7e21f2ac5d/asciidoc/modules/con_mg_generic-updates-in-vertx-http.adoc#httpmethod-is-available-as-a-interface

**Comment by vietj** [comment]
thanks!

**Comment by j-pel** [comment]
Checked, it works.

The issue is related to the helper files for the VSCode interface and is still there:
![image](https://user-images.githubusercontent.com/18239574/104459290-8cb56000-557a-11eb-9a33-5f534a9bcac9.png)
