### ISSUE TITLE
Incomplete information on Base64 encoding in Migration Guide

### ISSUE THREAD

**Issue by mansiag** [vert-x3/vertx-4-migration-guide#67]
### Questions

Unable to find Json.toBase64() method mentioned in the [migration guide](https://vert-x3.github.io/vertx-4-migration-guide/index.html#changes-in-json_changes-in-common-components)
```
Use the following example code to convert a Base64URL to Base64 encoder.
String base64url = someJsonObject.getString("base64encodedElement")
String base64 = Json.toBase64(base64url);
```
[https://vertx.io/docs/apidocs/io/vertx/core/json/Json.html](https://vertx.io/docs/apidocs/io/vertx/core/json/Json.html)
### Version

Which version(s) did you encounter this bug ?
4.1.0

**Comment by pmlopes** [comment]
@mansiag I'll update the docs. We planned to introduce such a method but in the end it was discussed that this method could introduce confusion, so instead I'll document how to manually convert from `base64url` to `base64` by adding the code:

```
base64urlString
  .replace('-', '+')
  .replace('_', '/');
```

As, this converts data between the 2 encoding formats.

**Comment by mansiag** [comment]
@pmlopes Can you please also provide more information on my second mail here on Decode - https://groups.google.com/g/vertx/c/JKcKfjE5wTo
