### ISSUE TITLE
Cassandra Client migration

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-4-migration-guide#7]

**Comment by tsegismont** [comment]
@Sammers21 can you take care of this please? There is some content in the guide already that you can inspire from. AFAIR the changes in Cassandra client are mostly impacting `CassandraClientOptions` and thus the creation of the client.

**Comment by Sammers21** [comment]
@tsegismont, yes, sure. I will take care of it.

**Comment by tsegismont** [comment]
Thank you!

**Comment by Sammers21** [comment]
@tsegismont, @vietj, please review #17 PR.
