### ISSUE TITLE
SLF4J Log Delegate vs Log4J2 Log Delegate in Vertx 4.3.2. Which one is better? Why?

### ISSUE THREAD

**Issue by sac10nikam** [vert-x3/vertx-4-migration-guide#74]
### Questions

**SLF4J Log Delegate vs Log4J2 Log Delegate** in Vertx 4.3.2. Which one is better? Why?

I am using Vertx 3.9.7. Having 'io.vertx.core.logging.Logger' is deprecated . I want to replace it with the new Logger API.

### Version

4.3.2

### Context

Logging in Vertx 4.3.2 - Migration from 3.9.7 to 4.3.2

### Do you have a reproducer?

NA

* Link to github project/gist

### Steps to reproduce

NA

### Extra

JVM 17

**Comment by sac10nikam** [comment]
@pendula95 @jponge Do you know this?

**Comment by tsegismont** [comment]
@sac10nikam in Vert.x 4, the vertx logging API is for internal usage only.

If your choice for migration is log4j2, add the dependencies to your project:

```xml
<dependencies>
  <dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-api</artifactId>
    <version>2.18.0</version>
  </dependency>
  <dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-core</artifactId>
    <version>2.18.0</version>
  </dependency>
</dependencies>
```

And then:

```java
/// imports
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

// logger creation
private static final Logger parentLogger = LogManager.getLogger("my-logger");
```

You no longer need to set a system property for vertx. It will pick up log4j2 automatically on startup as it finds it on the classpath.
